language: java
script: mvn test -f pom.xml
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Q4knSRO6hhSZFtIkm8uoXm3SfqWfx7BREkO2zZvks87I9rg42K7SWeBkj0CST3HNf4enQvDEc2Uh613BmeNIgEggSQes9eKyYoLw33rvpLx0X0mnf2ULQljcWIG7ZaPzZo3Vz/wTJKjpBakScvefd+tt9YRt2q+Ilu8q0ZLSyls="

addons:
  coverity_scan:
    project:
      name: "eXsio/nestedj"
      description: "Build submitted via Travis CI"
    notification_email: noneedto@notify.me
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

after_success:
  - bash <(curl -s https://codecov.io/bash)